# Generated by Django 4.0.5 on 2022-06-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='home_type',
            field=models.CharField(choices=[('Flat', 'Flat'), ('Bungalow', 'Bungalow'), ('Residential Land', 'Residential Land'), ('Commercial Land', 'Commercial Land'), ('Shop', 'Shop')], default='Flat', max_length=50),
        ),
    ]
