# Generated by Django 4.0.5 on 2022-06-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_home_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(choices=[('Pune', 'Pune'), ('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Banglore', 'Banglore'), ('Bhopal', 'Bhopal'), ('Kolhapur', 'Kolhapur')], default='Pune', max_length=50),
        ),
    ]
