# Generated by Django 4.0.5 on 2022-06-08 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_listing_photo_10_remove_listing_photo_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='country',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='open_house',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='zipcode',
        ),
    ]
